### PR TITLE
Create Docker composition which includes GeoServer for testing

### PR DESCRIPTION
**Pull request by vuilleumierc**

### CODE REVIEW

**Review by jwkaltz — COMMENTED** [review]
The script ./scripts/test.sh assumes a directory "data/ag", but this is not part of the repository. In fact, "data/ag" is in the .gitignore
Should the script be changed?

**Comment by vuilleumierc** [comment]
How would you change it? On my side I have copied all the AG input files in data/ag so it works. I added data/ag in the .gitignore so that we don't publish all this data here

**Comment by jwkaltz** [comment]
> How would you change it? On my side I have copied all the AG input files in data/ag so it works. I added data/ag in the .gitignore so that we don't publish all this data here

Maybe it is enough to add as a docu how it can be used, and/or add a user output in the script. This is what I tried so far:
* run: scripts/test.sh -> gives an error, maybe we can tell the user here to download some data first in the directory mentioned
* run: docker-compose -f tests/docker-compose.yaml up -> there are some errors "input contained no data", probably just a consequence of the missing directory
* open in browser: http://localhost:8380/web/
* login as admin/geoserver, click on "Layers" -> there is an error in the console "Error while getting feature type", probably just a consequence of the missing directory

I will retry after putting the data from aargau in an "ag" directory.

**Comment by vuilleumierc** [comment]
OK, I will also have look, because the data in data/ag should not be mandatory to run the test composition

**Comment by jwkaltz** [comment]
I got a bit further as follows, but I am still missing something:

Preparations for tests:
start the lyrx2sld service (as in the README)
copy all AG data to a subdirectory data/ag
mkdir data/geoserver_data_dir/styles/ag (otherwise there is an error when running the script)
run ./scripts/test.sh
stop the lyrx2sld service

Now to run, I did this, but same effect as before:
docker-compose -f tests/docker-compose.yaml up
There are some errors in the console such as java.io.EOFException: input contained no data
http://localhost:8380/web/
login as admin/geoserver
Click on Layers -> warning in the console "Error while getting feature type, flushing cache and retrying: {0}", nothing happening in UI.

**Comment by vuilleumierc** [comment]
I think the docker composition is missing a database for the layer data. Should we add this as well?
The database connection should not be required to edit and preview the styling (you can try by going to the page "Styles" instead of "Layers") - there you can upload the SLD files (which you have been created by lyrx2sld when running the bash script)

**Pull request closed without merging**
